### ISSUE TITLE
Tile errors are not communicated to the application

### ISSUE THREAD

**Issue by mick88** [wrobell/geotiler#11]
Some of my downloaded maps contain blank tiles with "Error downloading map tile" and terminal output shows the following error message:

> Cannot download a tile due to error: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

Normally I would expect the called script to raise an exception, but the library ignores it and generates map with a hole in it instead.

**Comment by wrobell** [comment]
That's design decision kept from Modestmaps era. I agree there should be some indication on the API level that not all images had downloaded successfully, but I would like to keep a possibility to continue if a tile failed to be loaded.

**Comment by mick88** [comment]
As an alternative design, can I suggest passing list of exceptions down to the calling application? This would give user the option to decide whether to keep the map or retry.
For instance:
```python
map_img = geotiler.render_map(geo_map)
if map_img.errors:
    raise map_img.erros[0]
map_img.save('out/map.png')
```

**Comment by wrobell** [comment]
The problem is bit more complex. Probably API extension is required.

I am thinking something about like follows

1. The default call
```
img = geotiler.render_map(map)
```
2. Or fetch tiles first
```
tiles = geotiler.fetch_tiles(map)  # generator, progress of fetching tiles can be controlled
img = geotiler.render_map(tiles)
```
3. Above allows to make custom processing possible
```
tiles = list(geotiler.fetch_tiles(map))
error_tiles = [t for t in tiles if t.error]

# render image first
img = geotiler.render_map(tiles)

# re-fetch tiles in error
if error_tiles:
    tiles = geotiler.fetch_tiles(map, tiles=tiles)  # tiles parameter is existing tiles

# re-render the image
img = geotiler.render_map(tiles)
```

**Comment by wrobell** [comment]
Above is probably too complicated what is requested in this ticket.

What about
```
img = geotiler.render_map(map, error_policy=RENDER_ERROR_TILE)  # current and default behaviour
img = geotiler.render_map(map, error_policy=RAISE_ERROR)  # will raise exception of first failed tile
```

**Comment by mick88** [comment]
How about an optional callable argument called when tile fetch fails? The default value could return a bitmap with placeholder. calling applications could use it to customise the placeholder or raise an error. The callable could accept parameters like x and y coordinates and exception.

**Comment by wrobell** [comment]
I would like to avoid callbacks, so this leads us to the design described in https://github.com/wrobell/geotiler/issues/11#issuecomment-322903370.

**Comment by wrobell** [comment]
I have just implemented `geotiler.fetch_tiles` function. Please see example at

https://github.com/wrobell/geotiler/blob/master/examples/ex-fetch-tiles.py
