### ISSUE TITLE
OSM-cycle asks for API key

### ISSUE THREAD

**Issue by nishadhka** [wrobell/geotiler#15]
Thank you very much for the library. 

The OSM cycle based background is having this issue of printing API Key required in the output, how to add the API Key, thank you
![imageout](https://user-images.githubusercontent.com/3928997/31110575-96ff9a36-a825-11e7-8352-5c346c28d0b8.png)

**Comment by wrobell** [comment]
GeoTiler switched to use ThunderForest OSM cycle tiles as osm.org uses them as well. Unfortunately, ThunderForest introduced API keys some time ago

https://www.thunderforest.com/docs/apikeys/

I would prefer to have basic supported maps to not use the API keys as this is a hassle for an user.

Looking at

- http://wiki.openstreetmap.org/wiki/Tile_servers
- http://wiki.openstreetmap.org/wiki/File:Tile_cycling.png

it seems we could switch to http://{a,b,c}.tile.opencyclemap.org/cycle/.

Unfortunately, the official OpenCycleMap webpage

https://www.opencyclemap.org/about/

indicates that ThunderForest should be used anyway. I will create TunderForest configuration file separately as I suspect that sooner or later the http://{a,b,c}.tile.opencyclemap.org/cycle/ tiles will be gone.

**Comment by wrobell** [comment]
See this commit https://github.com/wrobell/geotiler/commit/ae51ae97cf27645173048c413e509e0b384cbbba. API key support to be added later.

**Comment by wrobell** [comment]
API key support implemented in cbb6b49.

**Comment by nishadhka** [comment]
Thank you

**Comment by wrobell** [comment]
I have released GeoTiler 0.12.0 with support for API keys. This is documented at https://wrobell.dcmod.org/geotiler/usage.html#map-providers.

Create `$HOME/.config/geotiler/geotiler.ini` file and put Thunderforest API key
```
[api-key]
thunderforest = <api-key>
```
where `<api-key>` is the API key obtained from the Thunderforest website once you signup with them.
