### ISSUE TITLE
jupyter notebook

### ISSUE THREAD

**Issue by dfolch** [wrobell/geotiler#16]
I have been using geotiler for awhile now and really like it. If I save the map to the hard drive it looks great, but the image rendered in a Jupyter Notebook is low resolution. Does anyone know how to increase the resolution in the Notebook? Here is my workflow.
```
import geotiler
import matplotlib.pyplot as plt
%matplotlib inline

phx_tiler = geotiler.Map(center=(-112.00, 33.283), zoom = 12, size=(2000,2000))
phx_img = geotiler.render_map(phx_tiler)
plt.figure(figsize=(10,10))
plt.imshow(phx_img)
```

**Comment by wrobell** [comment]
Just in case, you can use this

```
from IPython import display
display.display(phx_img)
```

I have various results with Matplotlib, but nothing reproducible at the moment.

**Comment by wrobell** [comment]
To make it work with Matplotlib, drop axes and the border

```
import geotiler
import matplotlib.pyplot as plt
import matplotlib as mpl

%matplotlib inline

WIDTH, HEIGHT = 512, 512

dpi = mpl.rcParams['figure.dpi']

phx_tiler = geotiler.Map(center=(-112.00, 33.283), zoom=12, size=(WIDTH, HEIGHT))
phx_img = geotiler.render_map(phx_tiler)

fig = plt.figure(figsize=(WIDTH / dpi, HEIGHT / dpi))

ax = plt.Axes(fig, [0, 0 ,1 , 1])  # get rid of white border
ax.set_axis_off()  # drop axes
fig.add_axes(ax)
ax.imshow(phx_img)
```

**Comment by dfolch** [comment]
That is an amazing improvement on resolution. Thanks.

**Comment by wrobell** [comment]
BTW. This is not low resolution issue. The image is re-scaled without interpolation. Your original example will work much better if you use `interpolation='sinc'` parameter with `plt.imshow` call. You might want to use `figsize=(20, 20)` for `2000 x 2000` map image size though.

There are different interpolation algorithms, see: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.imshow.html.

**Comment by dfolch** [comment]
I updated the gist referenced in #17 with the `interpolation='sinc'` trick. With that change, a GeoPandas/GeoTiler plot is just two lines.
