### ISSUE TITLE
geopandas example

### ISSUE THREAD

**Issue by dfolch** [wrobell/geotiler#17]
I wrote a (long) tutorial on integrating GeoPandas and GeoTiler for mapping point and polygon data on a basemap. Also has code for high resolution mapping in the Jupyter Notebook (thanks to @wrobell). I hope someone here might find it useful.
https://gist.github.com/dfolch/ace80ca0307c571b6a1a719430c4052e

**Comment by wrobell** [comment]
This looks great. Thanks for sharing.
