### ISSUE TITLE
Error configuration file .config/geotiler/geotiler.ini does not exist

### ISSUE THREAD

**Issue by JuliApril** [wrobell/geotiler#19]
Hello, I ve installed geotiler, but when I m trying to run .py file there are some errors.
First
`configuration file .config/geotiler/geotiler.ini does not exist`
Second
`could't find .netrc file`

PS my code was from one of the example. I tried it in spyder (Python 3.6)
`import geotiler
map = geotiler.Map(center=(-6.069, 53.390), zoom=16, size=(512, 512))
map.extent
image = geotiler.render_map(map)`

What can be wrong? Thanks in advance for help!

**Comment by wrobell** [comment]
First message is warning I suspect? Not sure about the 2nd message.

Can you please provide full script you are running with errors (not warnings)? If it fails with an error what is the stacktrace?

**Comment by wrobell** [comment]
First warning is from `geotiler`. It just warns you that there is no configuration file. This optional for some of the map providers.

The `.netrc` warning probably comes from `aiohttp` library.

You can switch off warnings with appropriate via `logging` library.

**Comment by rudyryk** [comment]
Hello! Same here :) @wrobell If this is optional and nothing wrong with not having .ini file, then why fire the warning?

**Comment by wrobell** [comment]
Some map providers require an API key, then you need the config file.

The best would be to raise an error for providers, which require the API key and ignore when provider can be used without any additional configuration.

Will try to correct that in few days.

**Comment by wrobell** [comment]
Fixed via commit 076acad.
