### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by heitorPB** [wrobell/geotiler#22]
I have some questions about this library. Maybe they would be useful to improve the documentation of the library

- in `geotiler.Map()`:
  - What is the unit of the `size` parameter? image pixels?
  - some combinations of `extend` and `zoom` look very ugly. Is there a smart way of finding out ideal values of `zoom` or `size`?
- is there a way to extend the map extent? for example: i read the coordinates of a gpx file and get the boundaries of the track (min/max lat/long) and use that as map.extent. But i want a bigger area. I tried to increase by 10% the bbox, but `img = geotiler.render_map(mm)` crashes:

  ```
  DEBUG:asyncio:Using selector: EpollSelector
  DEBUG:geotiler.tile.img:combining tiles
  Killed
  ```

  maybe a `Map.zomm_out(zoom_percentage)` method? I tried to increase the bbox multiplying each entry by 1.1 or 0.9. It crashed. But when I summed 0.002, it worked. I chose the number by trial and error.
- maybe you should rename the internal `map` variables to `my_map` (or something else) to not confuse/overwrite with [map()](https://docs.python.org/3.5/library/functions.html#map). Also in the examples.
- it would be nice to add a note to the [docs](https://wrobell.dcmod.org/geotiler/index.html) that you need redis-server running for the Command Line Tools. And also a note in the readme about this online doc, it took me a while to find it.

**Comment by wrobell** [comment]
1. The size parameter is in image pixels. Please see https://wrobell.dcmod.org/geotiler/api.html#geotiler.Map.size.
2. Not sure how can I help with extend/zoom. Can you provide some examples?
3. For the crash. Can you provide some example to reproduce please?
4. The Redis server usage should be optional in general. Will try to unify the cli tools to behave in the same (i.e. `geotiler-lint` does not use caching by default).
