### ISSUE TITLE
Fix "RuntimeError: This event loop is already running"

### ISSUE THREAD

**Issue by geriskenderi** [wrobell/geotiler#24]
I don't know if this is a problem that has also happened to others, but in case you need a solution, you should go to geotiler/map.py and add the following to the imports:

```
import nest_asyncio
nest_asyncio.apply()
```

I also suggest to the authors to add the two lines above, in case this becomes a recurring problem. Making a pull request didn't seem necessary for this small issue.

**Comment by pintergreg** [comment]
I'm not familiar with asyncio, but without those two lines this package is completely unusable for me. Thanks.

**Comment by wrobell** [comment]
IMHO, that should not be needed.

Please show what you are doing exactly and the errors you are getting.

**Comment by pintergreg** [comment]
```python
import matplotlib.pyplot as plt
import geotiler
# import nest_asyncio
# nest_asyncio.apply()
bbox = 18.85, 47.35, 19.35, 47.65  # minX, minY, maxX, maxY
zoom = 12

lines = geotiler.Map(extent=bbox, zoom=zoom, provider="stamen-terrain-lines")
bg = geotiler.Map(extent=bbox, zoom=zoom, provider="stamen-terrain-background")
background = geotiler.render_map(bg)
```
![Képernyőkép_2020-11-02_15-33-17](https://user-images.githubusercontent.com/3854784/97880059-fca89e00-1d20-11eb-9196-7b3cf9614254.png)


But I'm using an interactive environment (Atom editor with Hydrogen to run lines on demand).
If I run this code as a script it's okay.
The nest_asyncio solves the problem in interactive mode.

**Comment by wrobell** [comment]
This is something you need to deal with in your interactive environment.

If it **does** support asyncio, use
```
background = await geotiler.render_map_async(bg)
```
(see https://wrobell.dcmod.org/geotiler/api.html#geotiler.render_map_async).

If it does **not** support asyncio, then it should not cause issues with `render_map`, IMHO.

Maybe you should instruct your interactive environment to use nested asyncio whenever you start a new session?

Anyway, this is out of scope for this library.

**Comment by pintergreg** [comment]
> Anyway, this is out of scope for this library.

You're right.

Anyway, it might be worth to add a note to readme about this. (Though I'm used to check the issues when I'm facing an error like this and this issue documents the situation and provides workaround.)

**Comment by wrobell** [comment]
I might add appropriate section in the future. I have a general idea of documentation overhaul, but this might take some time. For now I would suggest to create wiki entry.

This problem was reported before with JupyterLab if I am not mistaken, but it is first time someone proposed to use nested asyncio lib.
