### ISSUE TITLE
Size of tiles is hardcoded

### ISSUE THREAD

**Issue by Jacky2k** [wrobell/geotiler#26]
Hi,
a fried used this lib and we stumbled across a small problem: The size of the tiles is expected to be 256x256. There are, however, providers with different resolutions, usually to provide "retina" or "high-res" tiles. When adding such a provider, the library messes up the images. It seems like its cutting only 256x256 from the 512x512 tiles. We changed the two "return 256" statements in provider.py to 512 and it worked.
So I guess you should either add an additional option in the json files, which defines the resolution, or even better automatically detect it once an image is downloaded.

**Comment by wrobell** [comment]
Probably the best way is to add this flexibility when adding a new provider. Would you be able to provide details for such map provider?

**Comment by Jacky2k** [comment]
The tile service we used is:
https://tiles.lyrk.org/lr/8/131/84?apikey=e9f8eb3824344d18a5b4b657773caf30
Which we found here:
https://mc.bbbike.org/mc/?lon=10&lat=50&zoom=13&num=1&mt0=lyrk-retina
At the bottom of this page is a list of such tiles server, but we checked only the first one as it worked:
https://wiki.openstreetmap.org/wiki/High-resolution_tiles
The page states that this is an configuration parameter to Mapnik, but I was unable to figure out how to configure it.
