### ISSUE TITLE
Please use preferred tile.openstreetmap.org URL

### ISSUE THREAD

**Issue by Firefishy** [wrobell/geotiler#32]
See: https://github.com/openstreetmap/operations/issues/737

Example:
https://github.com/wrobell/geotiler/blob/b0e13ac3063744f3aeacd973e867cf84db90fe67/geotiler/tests/test_provider.py#L40

**Comment by wrobell** [comment]
@Firefishy Thanks for reporting this.
@lingwhatics  Thanks for the pull request.

It would be great if we had answer about tile usage policy first

1. Original question: https://github.com/openstreetmap/operations/issues/737#issuecomment-1234818175
2. Reminder: https://github.com/openstreetmap/operations/issues/737#issuecomment-1365889153

**Comment by wrobell** [comment]
Answer about tile usage policy: https://github.com/openstreetmap/operations/issues/737#issuecomment-1366498706
