### ISSUE TITLE
Stamen providers appear not to work now.

### ISSUE THREAD

**Issue by c-rodwell** [wrobell/geotiler#38]
Hi, I've been using Geotiler in a map application. Recently I noticed that I couldn't load a map from any of the Stamen providers.

these providers all seem not to work now:
'stamen-terrain', 'stamen-terrain-background', 'stamen-terrain-lines', 'stamen-toner', 'stamen-toner-lite', 'stamen-watercolor'

I remember all of them working before, and 'osm' provider still works.

I am using Windows 10, Python 3.9.1. I first noticed the issue on Geotiler 0.14.7. I updated to 0.15.0 using pip and still had the issue.

I think it's due to Stamen changing their website or removing the map service. On stamen.org I used to see a demo of terrain, toner, and watercolor maps but don't see it now.

So this is probably out of your control, but I wanted to check if everyone sees the same issue. 
Fortunately I can still use the OSM provider for now.

example Python code, which shows osm working vs stamen-terrain not working.

m = geotiler.Map(center=(0.0, 0.0), zoom=6, size=(500,500), provider="osm")
i = geotiler.render_map(m)
i.show()        -> shows a map image of Atlantic Ocean.

m = geotiler.Map(center=(0.0, 0.0), zoom=6, size=(500,500), provider="stamen-terrain")
i = geotiler.render_map(m)
Cannot download a tile due to error: Unable to download http://b.tile.stamen.com/terrain/6/31/32.png (error: Cannot connect to host b.tile.stamen.com:80 ssl:default [getaddrinfo failed])
Cannot download a tile due to error: Unable to download http://c.tile.stamen.com/terrain/6/32/31.png (error: Cannot connect to host c.tile.stamen.com:80 ssl:default [getaddrinfo failed])
Cannot download a tile due to error: Unable to download http://a.tile.stamen.com/terrain/6/31/31.png (error: Cannot connect to host a.tile.stamen.com:80 ssl:default [getaddrinfo failed])
Cannot download a tile due to error: Unable to download http://d.tile.stamen.com/terrain/6/32/32.png (error: Cannot connect to host d.tile.stamen.com:80 ssl:default [getaddrinfo failed])
i.show()    ->  shows "error rendering map" image.

**Comment by wrobell** [comment]
They are moved to Stadia Maps

- https://stamen.com/here-comes-the-future-of-stamen-maps/
- https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/

I will try to correct this within a week or so.

**Comment by wrobell** [comment]
Fixed with commit 95d44e3.

Please note

- API key is required
- attribution has changed
