### ISSUE TITLE
Failure while reading provider config

### ISSUE THREAD

**Issue by Eierkopp** [wrobell/geotiler#8]
When system's character encoding differs from utf8, osm.json fails to load. Fix is to open the file with encoding="utf8".

    --- geotiler/provider.py~ 2016-10-03 13:20:22.589822292 +0200
    +++ geotiler/provider.py  2016-10-04 09:42:04.890128325 +0200
    @@ -109,7 +109,7 @@
         fn = os.path.join(base_dir(), id + '.json')
         if __debug__:
             logger.debug('loading map provider "{}" from {}'.format(id, fn))
    -    with open(fn) as f:
    +    with open(fn, encoding="utf8") as f:
             data = json.load(f)
             provider = MapProvider(data)
             return provider

**Comment by wrobell** [comment]
Thanks. Fixed in b7b17a9778d9c7c3dd3fe09e19b3b8e0fb736be3.
